services:
  postgres:
    image: postgres:latest
    container_name: tanstack_pg
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - tanstack_pg_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    name: tanstack_pg

volumes:
  tanstack_pg_data:
